# Generated by Django 2.2.5 on 2019-10-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_styleimage_style'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StyleImage',
            new_name='DoodleImage',
        ),
    ]
