# Generated by Django 2.2.5 on 2019-10-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191016_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doodleimage',
            name='image',
            field=models.ImageField(upload_to='doodle/samples'),
        ),
    ]
