# Generated by Django 2.2.5 on 2019-10-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Avatar/samples/dataset/selfie2anime/testA/'),
        ),
    ]
