# Generated by Django 2.2.5 on 2019-10-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191010_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='dataset/selfie2anime/testA/'),
        ),
    ]
